import numpy as np
import subprocess
from PIL import Image, ImageColor

power_colors = {
    "#24ee02": "ireland",
    "#c0b5f1": "liverpool",
    "#071ef8": "edinburgh",
    "#80d7f2": "london",

    "#4ac8bd": "north norway",
    "#45e5a9": "north sweden",
    "#fde0a6": "denmark",
    "#ff633a": "west berlin",
    "#841b3a": "west munich",
    "#985e2c": "belgium",
    "#ec8b08": "holland",
    "#e34100": "east kiel",
    "#fe4237": "east berlin",
    "#744c55": "west kiel",
    "#ff0cc3": "wait",
    "#cf5500": "aetherlands",
    "#d7948b": "east munich",
    "#b38337": "taani",
    "#a9a601": "south sweden",
    "#3ba634": "south norway",

    "#f3eae5": "sofia",
    "#8d6f65": "bucharest",
    "#df8560": "belgrade",
    "#b7702e": "salzburg",
    "#00acde": "linz",
    "#6e8638": "graz",
    "#ddfe3b": "craiova",
    "#e39447": "stara zagora",
    "#6bca30": "traun",
    "#e64636": "zrenjanin",
    "#344ebf": "leoben",
    "#c3de6b": "wolfsburg",
    "#ccffcb": "brasov",
    "#e16242": "baden",
    "#134162": "leonding",
    "#8d0283": "ruse",
    "#328066": "bregenz",
    "#4257cc": "novi pazar",
    "#77e5be": "innsbruck",
    "#e59246": "novi sad",
    "#bc6c4b": "plovdiv",
    "#c87f70": "iasi",
    "#f5c5b1": "klagenfurt",
    "#3dafaf": "villach",
    "#fdb64c": "dornbirn",
    "#55ba38": "nis",
    "#910079": "varna",
    "#e6481b": "wels",
    "#c57760": "sankt polten",
    "#d1b806": "constanta",
    "#e818f4": "steyr",
    "#67c451": "feldkirch",
    "#cf0376": "wiener neustadt",
    "#dd8e55": "kragujevac",
    "#a7ff97": "timisoara",
    "#d21a1a": "bugas",
    "#f1cee6": "crescent",
    
    "#4c85a3": "lisbon",
    "#cfd4fc": "cordoba",
    "#a1501b": "montpellier",
    "#9b0aa7": "rennes",
    "#5c6ccb": "strasbourg",
    "#e94900": "braga",
    "#60bcff": "barcelona",
    "#f4c956": "lyon",
    "#533456": "bordeaux",
    "#fbfcdc": "lille",
    "#02e5d1": "almada",
    "#0e655c": "valencia",
    "#fe37f4": "nice",
    "#01afee": "nantes",
    "#d6a759": "reims",
    "#a2aeea": "coimbra",
    "#5148c5": "seville",
    "#d81bf4": "toulouse",
    "#a302fd": "le mans",
    "#5383ff": "nimes",
    "#5c914b": "squaris",

    "#89f65d": "venus",
    "#03f9b0": "turin",
    "#1c7717": "rome",
    "#f8ed46": "milan",
    "#fec434": "fouris",
    "#4c1978": "parma",
    "#4811f3": "prato",
    "#346178": "padua",
    "#b4cf5a": "threenis",
    "#caa557": "naples",
    "#8dacfc": "florence",
    "#8b93a6": "venice",
    "#3bb260": "tunis",
    "#d5d3c4": "verona",
    "#67b001": "vatican",
    "#4648cf": "messina",
    "#a69a34": "wonis",
    "#8d9f2f": "bari",
    "#dfd236": "genoa",
    "#e0982c": "palermo",
    "#e3fedb": "crystal",

    "#60518c": "devil petersburg",
    "#fdff32": "tolonen",
    "#c826c7": "kazan",
    "#db6b2b": "novgorod",
    "#abff8f": "samara",
    "#c1b604": "enodak",
    "#359e97": "tyumen",
    "#076320": "saratov",
    "#c0d961": "warsaw",
    "#e3fedf": "volgogrod",
    "#e10c1e": "rostov",
    "#ed7b22": "omsk",
    "#58d2fb": "ufa",
    "#c6af85": "sarre",

    "#e30629": "chicken",
    "#ebc5b0": "eskisehir",
    "#f75f09": "istanbul",
    "#616542": "adana",
    "#ce74f8": "phesant",
    "#27cfda": "samsun",
    "#e8ee0e": "konya",
    "#02fdc8": "denizli",
    "#a089f3": "partridge",
    "#76b5fc": "van",
    "#95b6e3": "antalya",
    "#2acca7": "kayseri",
    "#0070f0": "grouse",
    "#dd02e4": "bursa",
    "#ddc0f8": "erzurum",
    "#f0beef": "diyarbakir",
    "#045e66": "quail",
    "#faead1": "izmir",
    "#89dcfe": "mersin",
    "#3c79ee": "smyrna",
    "#5a4e4e": "peacock",
    "#1c00f2": "gaziantep",
    "#19cfc2": "ankarna",
    "#a2fe5b": "marash",
    "#838aa4": "fireback",
    "#40854e": "constantinople",
    "#534175": "adapazari",
    "#00ebdf": "sanliurfa",
    "#b99e0f": "lighthouse",
    "#d1eeb8": "nile",
    "#da0640": "sparta",
    "#08942b": "athens",
    "#80df9b": "crossroads",
    "#ab89ea": "syria",
}
power_colors = {ImageColor.getrgb(k):v for (k, v) in power_colors.items()}

alliance_colors = {
    "britain": "#f0e000",
    "jupiter": "#87522c",
    "jupiter's moons": "#b9815c",
    "grand duchy of sweden": "#fe1a95",
    "north austria": "#322f6b",
    "wrtlbpp": "#6b66a5",
    "rift": "#4a3838",
    "spiral": "#f050ec",
    "australians": "#6c9abc",
    "one forty-six": "#416b1f",
    "warsaw pact": "#6335fe",
    "l'empire": "#17a5e5",
    "fire": "#40db36",
    "fire fighters": "#a036db",
    "t1: kuzey": "#c9011e",
    "t2: nightingale": "#fe0026",
    "t3: conure": "#fe4a65",
    "t4: rum": "#fe93a4",
    "t5: stpb": "#fec7cf",
    "t6: maranga": "#fec2ae",
    "t7: the gate": "#fe9e7b",
    "t8: rim": "#fe8054",
    "unaligned": "#ffffff",
    "dead": "#000000"
}
alliance_colors = {k:ImageColor.getrgb(v) for (k, v) in alliance_colors.items()}

allegiances = {
    "ireland": "warsaw pact",
    "liverpool": ["britain", "l'empire"],
    "edinburgh": "britain",
    "london": "britain",
    
    "north norway": "grand duchy of sweden",
    "north sweden": "grand duchy of sweden",
    "denmark": "grand duchy of sweden",
    "west berlin": "jupiter",
    "west munich": "jupiter",
    "belgium": "jupiter",
    "holland": "jupiter",
    "east kiel": "jupiter",
    "east berlin": "jupiter",
    "west kiel": "jupiter",
    "wait": "jupiter",
    "aetherlands": "jupiter",
    "east munich": "jupiter",
    "taani": "unaligned",
    "south sweden": "unaligned",
    "south norway": "jupiter's moons",

    "sofia": "rift",
    "bucharest": "rift",
    "belgrade": ["rift", "spiral", "l'empire", "one forty-six", "t8: rim", "fire", "warsaw pact"],
    "salzburg": "rift",
    "linz": ["rift", "australians"],
    "graz": "rift",
    "craiova": ["t8: rim", "wrtlbpp"],
    "stara zagora": "north austria",
    "traun": "wrtlbpp",
    "zrenjanin": "north austria",
    "leoben": "wrtlbpp",
    "wolfsburg": "north austria",
    "brasov": "one forty-six",
    "baden": ["australians", "rift"],
    "leonding": "australians",
    "ruse": "australians",
    "bregenz": "australians",
    "novi pazar": ["australians", "rift"],
    "innsbruck": "spiral",
    "novi sad": "spiral",
    "plovdiv": "spiral",
    "iasi": "spiral",
    "klagenfurt": "spiral",
    "villach": "spiral",
    "dornbirn": "spiral",
    "nis": "unaligned",
    "varna": "spiral",
    "wels": "spiral",
    "sankt polten": "spiral",
    "constanta": "spiral",
    "steyr": "one forty-six",
    "feldkirch": "one forty-six",
    "wiener neustadt": "unaligned",
    "kragujevac": "one forty-six",
    "timisoara": "one forty-six",
    "bugas": "one forty-six",
    "crescent": "one forty-six",

    "lisbon": "l'empire",
    "cordoba": "l'empire",
    "montpellier": "l'empire",
    "rennes": "l'empire",
    "strasbourg": "l'empire",
    "braga": "l'empire",
    "barcelona": "l'empire",
    "lyon": "l'empire",
    "bordeaux": "l'empire",
    "lille": "l'empire",
    "almada": "l'empire",
    "valencia": "l'empire",
    "nice": "l'empire",
    "nantes": "l'empire",
    "reims": "l'empire",
    "coimbra": "fire",
    "seville": "l'empire",
    "toulouse": "l'empire",
    "le mans": "l'empire",
    "nimes": "l'empire",
    "squaris": "l'empire",

    "venus": "l'empire",
    "turin": "fire",
    "rome": "fire",
    "milan": "fire",
    "fouris": "fire",
    "parma": "fire",
    "prato": "fire",
    "padua": "fire",
    "threenis": "fire",
    "naples": "fire",
    "florence": "fire fighters",
    "venice": "fire",
    "tunis": "grand duchy of sweden",
    "verona": "fire",
    "vatican": "fire",
    "messina": ["fire fighters", "l'empire"],
    "wonis": "fire",
    "bari": "fire",
    "genoa": "fire",
    "palermo": "fire",
    "crystal": "fire",

    "devil petersburg": "warsaw pact",
    "tolonen": "warsaw pact",
    "kazan": "warsaw pact",
    "novgorod": "warsaw pact",
    "samara": "unaligned",
    "enodak": "warsaw pact",
    "tyumen": "warsaw pact",
    "saratov": "warsaw pact",
    "warsaw": "warsaw pact",
    "volgogrod": "warsaw pact",
    "rostov": "warsaw pact",
    "omsk": "warsaw pact",
    "ufa": "warsaw pact",
    "sarre": "warsaw pact",

    "chicken": "t1: kuzey",
    "eskisehir": "unaligned",
    "istanbul": "t1: kuzey",
    "adana": "t1: kuzey",
    "phesant": "unaligned",
    "samsun": "t2: nightingale",
    "konya": "t2: nightingale",
    "denizli": "t2: nightingale",
    "partridge": "t2: nightingale",
    "van": "unaligned",
    "antalya": "t3: conure",
    "kayseri": "t3: conure",
    "grouse": "t3: conure",
    "bursa": "t4: rum",
    "erzurum": "t4: rum",
    "diyarbakir": "t4: rum",
    "quail": "t4: rum",
    "izmir": "t5: stpb",
    "mersin": "t5: stpb",
    "smyrna": "t5: stpb",
    "peacock": "t5: stpb",
    "gaziantep": "t6: maranga",
    "ankarna": "t6: maranga",
    "marash": "t6: maranga",
    "fireback": "unaligned",
    "constantinople": "t7: the gate",
    "adapazari": "t7: the gate",
    "sanliurfa": "t7: the gate",
    "lighthouse": "warsaw pact",
    "nile": "t8: rim",
    "sparta": "t8: rim",
    "athens": "t8: rim",
    "crossroads": "t8: rim",
    "syria": "t7: the gate",   
}

STRIPE_WIDTH = 15
def recolor(x, y, pixel):
    pixel = tuple(int(v) for v in pixel)
    if pixel not in power_colors:
        return pixel
    alliance = allegiances[power_colors[pixel]]
    if isinstance(alliance, list):
        n = len(alliance)
        stripe_idx = (x + y) % (STRIPE_WIDTH * n) // STRIPE_WIDTH
        alliance = alliance[stripe_idx]
    return np.array(alliance_colors[alliance])

def recolor_image(original_filename, recolored_filename):
    image = Image.open(original_filename).convert("RGB")
    data = np.array(image)
    for x in range(data.shape[0]):
        for y in range(data.shape[1]):
            data[x, y] = recolor(x, y, data[x, y])

    image2 = Image.fromarray(np.uint8(data))
    image2.save(recolored_filename)


recolor_image("starter_map.png", "starter_map_recolored.png")
subprocess.call(["krita","7DC_original_owner.kra","--export","--export-filename","7DC_original_owner.png",])

recolor_image("current_map.png", "current_map_recolored.png")
subprocess.call(["krita", "7DC_current_owner.kra","--export", "--export-filename", "7DC_current_owner.png"])

subprocess.call(["magick", "7DC_original_owner.png", "7DC_current_owner.png", "+append", "7DC.png"])